/* Literary temperament questions · fr */
const LIT_Q = {
  q01:{id:'q01',q:'Quand la pluie frappe la fenêtre la nuit, vous pensez d\'abord à—',type:'Pensée nocturne',opts:[
    {t:'Des lettres jamais envoyées, des mots restés en suspens',d:[1, 3, 1, 2, 2, 1],next:'q02'},
    {t:'Une vieille route, une silhouette qui s\'éloigne',d:[0, 3, 1, 2, 2, 0],next:'q03'},
    {t:'Combien de gens dans la ville veillent encore',d:[2, 1, 2, 2, 3, 0],next:'q04'},
    {t:'La pluie elle-même, comme un dialogue sans fin',d:[1, 2, 3, 2, 0, 2],next:'q05'},
    {t:'Trop bizarre',d:[1, 1, 2, 3, 1, 2],next:'q30'},
  ]},
  q02:{id:'q02',q:'Si vous écriviez une demi-phrase pour cette humeur, elle s\'arrêterait à—',type:'Humeur',opts:[
    {t:'« Voilà. »',d:[2, 1, 2, 1, 1, 1],next:'q06'},
    {t:'« Quel dommage… »',d:[1, 3, 1, 2, 2, 0],next:'q07'},
    {t:'« Tant pis. »',d:[1, 1, 1, 2, 2, 1],next:'q08'},
    {t:'« Attends — ce n\'est pas ça. »',d:[2, 0, 3, 1, 0, 2],next:'q09'},
    {t:'Aucune idée par où commencer',d:[1, 1, 2, 3, 1, 2],next:'q31'},
  ]},
  q03:{id:'q03',q:'En entrant dans la foule, vous ressemblez plutôt à—',type:'Dans la foule',opts:[
    {t:'Un observateur froid qui note',d:[2, 1, 2, 2, 1, 1],next:'q06'},
    {t:'Quelqu\'un facilement touché ou blessé',d:[0, 3, 1, 1, 3, 0],next:'q07'},
    {t:'Un passant poli et distant',d:[1, 2, 1, 3, 0, 1],next:'q08'},
    {t:'Celui qui trame des histoires en secret',d:[1, 2, 3, 2, 0, 2],next:'q09'},
    {t:'Aucune idée',d:[1, 1, 2, 3, 1, 2],next:'q30'},
  ]},
  q04:{id:'q04',q:'Un bon livre interrompu à mi-chemin — vous pensez—',type:'Notes de lecture',opts:[
    {t:'Il faut un endroit calme pour le finir',d:[1, 2, 1, 2, 1, 1],next:'q06'},
    {t:'S\'arrêter au suspense laisse un meilleur arrière-goût',d:[1, 3, 1, 2, 0, 2],next:'q07'},
    {t:'Que fait ce personnage en ce moment ?',d:[0, 2, 2, 2, 2, 1],next:'q08'},
    {t:'Marquer cette page — j\'y reviendrai',d:[2, 1, 3, 1, 1, 2],next:'q09'},
    {t:'Esprit complètement vide',d:[1, 1, 2, 3, 1, 2],next:'q31'},
  ]},
  q05:{id:'q05',q:'Le mot « nostalgie » évoque d\'abord non un lieu, mais—',type:'Nostalgie',opts:[
    {t:'Un ton auquel on ne peut plus revenir',d:[0, 3, 1, 2, 2, 0],next:'q06'},
    {t:'Vieilles choses, vieux sons, vieilles odeurs',d:[0, 3, 0, 1, 3, 0],next:'q07'},
    {t:'Votre jeune moi, brusque et sincère',d:[1, 2, 1, 2, 2, 1],next:'q08'},
    {t:'Le temps lui-même qui recule',d:[1, 2, 3, 2, 1, 2],next:'q09'},
    {t:'De quoi parle-t-on ?',d:[1, 1, 2, 3, 1, 2],next:'q30'},
  ]},
  q06:{id:'q06',q:'Quel silence connaissez-vous le mieux—',type:'Silence',opts:[
    {t:'Deux personnes silencieuses, mais qui se comprennent',d:[0, 2, 1, 2, 3, 0],next:'q10'},
    {t:'Ces secondes de lucidité dans le bruit',d:[1, 1, 2, 3, 0, 1],next:'q10'},
    {t:'Le long moment après avoir avalé ses mots',d:[2, 2, 1, 2, 2, 0],next:'q30'},
    {t:'Vouloir parler sans trouver le mot juste',d:[1, 2, 3, 2, 0, 2],next:'q31'},
    {t:'Fuir d\'abord, réfléchir après',d:[1, 1, 2, 3, 1, 2],next:'q31'},
  ]},
  q07:{id:'q07',q:'Quand vous écrivez, la première chose qui tombe est souvent—',type:'À la plume',opts:[
    {t:'Une question qui ne cède pas',d:[3, 0, 2, 0, 1, 1],next:'q11'},
    {t:'Une scène concrète : fenêtre, lampe, pluie',d:[0, 3, 1, 2, 1, 1],next:'q11'},
    {t:'Un vers sans début ni fin',d:[0, 3, 2, 1, 1, 2],next:'q30'},
    {t:'Une idée étrange mais captivante',d:[1, 1, 3, 1, 0, 3],next:'q31'},
    {t:'Peu importe, n\'importe lequel',d:[1, 1, 2, 3, 1, 2],next:'q30'},
  ]},
  q08:{id:'q08',q:'Quand la peine ne peut se dire, vous—',type:'Retenue',opts:[
    {t:'L\'écrivez ou la retournez en silence',d:[2, 2, 2, 2, 1, 2],next:'q12'},
    {t:'Faites semblant et continuez la vie',d:[1, 1, 0, 1, 3, 0],next:'q12'},
    {t:'Vous éloignez jusqu\'à ce que ça coule',d:[0, 2, 1, 3, 1, 0],next:'q30'},
    {t:'Riez soudain pour détourner l\'ambiance',d:[1, 1, 0, 2, 2, 2],next:'q31'},
    {t:'Je suis juste là pour faire nombre',d:[1, 1, 2, 3, 1, 2],next:'q31'},
  ]},
  q09:{id:'q09',q:'Quelle lumière vous détend le plus facilement—',type:'Lumière',opts:[
    {t:'Le crépuscule, le ciel entre clair et sombre',d:[0, 3, 1, 2, 1, 1],next:'q13'},
    {t:'La première lumière dans la brume du matin',d:[0, 3, 1, 1, 2, 1],next:'q13'},
    {t:'Le cercle chaud d\'une lampe la nuit',d:[0, 2, 2, 3, 1, 1],next:'q30'},
    {t:'Le blanc de midi, trop cru pour se cacher',d:[2, 1, 2, 1, 2, 2],next:'q31'},
    {t:'Trop bizarre',d:[1, 1, 2, 3, 1, 2],next:'q30'},
  ]},
  q10:{id:'q10',q:'Si vous vous compariez à une saison, vous seriez plutôt—',type:'Saisons',opts:[
    {t:'Fin printemps : abondance déjà teintée de déclin',d:[1, 3, 1, 1, 2, 1],next:'q14'},
    {t:'Long été : lourd, interminable, réticent à partir',d:[2, 2, 2, 1, 1, 2],next:'q14'},
    {t:'Profond automne : net, clair, un peu rétrospectif',d:[1, 2, 2, 2, 2, 1],next:'q32'},
    {t:'Fin d\'hiver : froid, immobile, mais porteur de renouveau',d:[2, 1, 3, 2, 1, 2],next:'q33'},
    {t:'Aucune idée par où commencer',d:[1, 1, 2, 3, 1, 2],next:'q31'},
  ]},
  q11:{id:'q11',q:'En apprenant une catastrophe lointaine, votre première réaction—',type:'Nouvelles lointaines',opts:[
    {t:'Demander pourquoi, refuser d\'accepter facilement',d:[3, 0, 2, 0, 2, 1],next:'q15'},
    {t:'Un cœur lourd qui met longtemps à se relever',d:[1, 3, 1, 1, 3, 0],next:'q15'},
    {t:'Se taire et recomposer les détails',d:[2, 1, 2, 2, 2, 1],next:'q32'},
    {t:'Trouver cela absurde, sans pouvoir en rire',d:[2, 1, 3, 2, 1, 3],next:'q33'},
    {t:'Aucune idée',d:[1, 1, 2, 3, 1, 2],next:'q30'},
  ]},
  q12:{id:'q12',q:'Une belle histoire — par où voudriez-vous qu\'elle commence—',type:'Premier trait',opts:[
    {t:'Un petit fait qui reflète toute une époque',d:[3, 1, 1, 1, 3, 0],next:'q16'},
    {t:'Une rencontre où l\'atmosphère précède l\'intrigue',d:[1, 3, 1, 2, 1, 1],next:'q16'},
    {t:'Une énigme ou un détail déplacé',d:[1, 1, 3, 2, 0, 3],next:'q32'},
    {t:'L\'instant où le quotidien se fissure',d:[2, 2, 1, 2, 2, 2],next:'q33'},
    {t:'Esprit complètement vide',d:[1, 1, 2, 3, 1, 2],next:'q31'},
  ]},
  q13:{id:'q13',q:'En disant adieu à un ami, vous—',type:'Adieu',opts:[
    {t:'Dites peu, mais regardez une fois de plus',d:[1, 2, 1, 2, 2, 0],next:'q17'},
    {t:'Des mots légers pour couvrir le poids',d:[1, 2, 0, 2, 2, 2],next:'q17'},
    {t:'Parlez soudain d\'une chose sans rapport',d:[1, 3, 1, 2, 1, 2],next:'q32'},
    {t:'Faites de « au revoir » un « à bientôt »',d:[0, 3, 1, 1, 2, 1],next:'q33'},
    {t:'De quoi parle-t-on ?',d:[1, 1, 2, 3, 1, 2],next:'q30'},
  ]},
  q14:{id:'q14',q:'Au réveil d\'un rêve, sur l\'oreiller reste souvent—',type:'Au réveil',opts:[
    {t:'Une émotion sans nom',d:[0, 3, 1, 2, 1, 2],next:'q18'},
    {t:'Une image nette, comme une vieille photo',d:[0, 3, 1, 2, 2, 1],next:'q18'},
    {t:'Une réplique du rêve, encore mémorisée',d:[1, 2, 2, 2, 1, 2],next:'q22'},
    {t:'Seulement le vide, mais un sentiment de perte',d:[1, 2, 3, 3, 0, 2],next:'q23'},
    {t:'Fuir d\'abord, réfléchir après',d:[1, 1, 2, 3, 1, 2],next:'q31'},
  ]},
  q15:{id:'q15',q:'À un coin de rue où la lumière est juste, vous—',type:'Coin de rue',opts:[
    {t:'Vous arrêtez pour voir la foule et les ombres',d:[1, 2, 1, 2, 1, 0],next:'q19'},
    {t:'Pensez à quelqu\'un d\'autrefois, sans lien avec l\'instant',d:[0, 3, 1, 2, 2, 0],next:'q19'},
    {t:'Sortez le téléphone, craignant de ne pas saisir l\'ambiance',d:[1, 2, 1, 3, 0, 1],next:'q22'},
    {t:'Sentez que ce moment ne doit pas être troublé',d:[0, 2, 2, 3, 1, 1],next:'q23'},
    {t:'Peu importe, n\'importe lequel',d:[1, 1, 2, 3, 1, 2],next:'q30'},
  ]},
  q16:{id:'q16',q:'Votre premier instinct devant « l\'absurde » est—',type:'L\'absurde',opts:[
    {t:'L\'état normal des choses — pas de surprise',d:[2, 1, 2, 1, 2, 2],next:'q20'},
    {t:'Le vide sous une surface splendide',d:[2, 2, 1, 2, 1, 2],next:'q20'},
    {t:'Une blague froide du destin',d:[1, 2, 2, 2, 1, 3],next:'q22'},
    {t:'Celui qui se cache derrière l\'absurde',d:[3, 0, 2, 1, 2, 2],next:'q23'},
    {t:'Je suis juste là pour faire nombre',d:[1, 1, 2, 3, 1, 2],next:'q31'},
  ]},
  q17:{id:'q17',q:'Si vous deviez renoncer à une chose, vous lâcheriez le moins—',type:'Choix',opts:[
    {t:'Le courage de dire la vérité',d:[3, 0, 2, 0, 2, 1],next:'q21'},
    {t:'La sensibilité et l\'attachement à la beauté',d:[0, 3, 2, 1, 1, 2],next:'q21'},
    {t:'Les liens avec quelques êtres choisis',d:[0, 2, 0, 1, 4, 0],next:'q24'},
    {t:'La place pour penser par soi-même',d:[2, 1, 3, 2, 0, 2],next:'q25'},
    {t:'Trop bizarre',d:[1, 1, 2, 3, 1, 2],next:'q30'},
  ]},
  q18:{id:'q18',q:'Seul, ce que vous préférez, c\'est—',type:'Solitude',opts:[
    {t:'Ne rien faire, laisser le temps couler',d:[0, 2, 2, 3, 1, 0],next:'q22'},
    {t:'Lire, écouter le vent, vous parler',d:[1, 2, 3, 2, 1, 1],next:'q22'},
    {t:'Mettre de l\'ordre dans les petits jours',d:[2, 0, 1, 1, 2, 0],next:'q26'},
    {t:'Laisser errer la pensée, noter des idées',d:[1, 2, 3, 2, 0, 3],next:'q27'},
    {t:'Aucune idée par où commencer',d:[1, 1, 2, 3, 1, 2],next:'q31'},
  ]},
  q19:{id:'q19',q:'Si vous ne pouviez garder que parler ou écrire—',type:'Expression',opts:[
    {t:'Écrire. À l\'oral, les mots se déforment',d:[1, 2, 2, 2, 1, 2],next:'q23'},
    {t:'Parler. Écrire est trop lent pour le cœur',d:[0, 3, 1, 1, 2, 1],next:'q23'},
    {t:'Peu des deux — le silence est plus honnête',d:[1, 1, 2, 3, 1, 1],next:'q26'},
    {t:'Autrement : dessiner, marcher ou simplement voir',d:[1, 2, 3, 2, 0, 2],next:'q27'},
    {t:'Aucune idée',d:[1, 1, 2, 3, 1, 2],next:'q30'},
  ]},
  q20:{id:'q20',q:'Quel type de phrase vous touche le plus facilement ?',type:'Goût des mots',opts:[
    {t:'Directe, tranchante, avec une pointe',d:[3, 0, 1, 1, 1, 2],next:'q24'},
    {t:'Calme, dense, comme un long plan',d:[1, 3, 1, 0, 3, 0],next:'q24'},
    {t:'Froide, belle, avec un peu de distance',d:[2, 2, 1, 3, 0, 1],next:'q28'},
    {t:'Abstraite, sautillante, qui fait penser',d:[1, 1, 3, 2, 0, 3],next:'q29'},
    {t:'Esprit complètement vide',d:[1, 1, 2, 3, 1, 2],next:'q31'},
  ]},
  q21:{id:'q21',q:'Dans une équipe, vous jouez le plus souvent—',type:'Collaboration',opts:[
    {t:'Celui qui pointe les problèmes',d:[3, 0, 1, 0, 1, 1],next:'q25'},
    {t:'Celui qui adoucit l\'ambiance',d:[0, 2, 0, 1, 3, 0],next:'q25'},
    {t:'Celui qui travaille en silence',d:[1, 0, 0, 1, 2, 0],next:'q28'},
    {t:'Celui qui propose des idées bizarres',d:[1, 2, 2, 1, 0, 3],next:'q29'},
    {t:'De quoi parle-t-on ?',d:[1, 1, 2, 3, 1, 2],next:'q30'},
  ]},
  q22:{id:'q22',q:'Un après-midi vide — vous remarquez d\'abord—',type:'Après-midi',opts:[
    {t:'La lumière glissant lentement sur le sol',d:[0, 2, 2, 3, 1, 1],next:'q26'},
    {t:'Des bruits lointains et faibles de la ville',d:[1, 2, 1, 2, 2, 0],next:'q26'},
    {t:'Ce que vous n\'avez pas encore achevé',d:[2, 1, 2, 2, 2, 1],next:'q34'},
    {t:'Le temps qui soudain ralentit',d:[1, 2, 3, 2, 1, 2],next:'q35'},
    {t:'Fuir d\'abord, réfléchir après',d:[1, 1, 2, 3, 1, 2],next:'q31'},
  ]},
  q23:{id:'q23',q:'Un vieux sophora au bord de la route — vous—',type:'Route ancienne',opts:[
    {t:'Vous reposez sous lui, écoutant le vent raconter',d:[0, 3, 2, 4, 3, 2],next:'q27'},
    {t:'Glissez une feuille dans des pages inachevées',d:[1, 4, 2, 3, 2, 4],next:'q27'},
    {t:'Vous souvenez d\'un adieu et restez longtemps',d:[1, 4, 1, 3, 3, 2],next:'q34'},
    {t:'Continuez sans vous retourner',d:[3, 2, 2, 2, 4, 2],next:'q35'},
    {t:'Peu importe, n\'importe lequel',d:[1, 1, 2, 3, 1, 2],next:'q30'},
  ]},
  q24:{id:'q24',q:'Le papier de la fenêtre frémit au vent, comme une page non lue. Vous—',type:'Papier de fenêtre',opts:[
    {t:'Le retenez, craignant qu\'il s\'envole',d:[1, 4, 1, 3, 2, 2],next:'q28'},
    {t:'Le laissez bruire en fond',d:[0, 3, 3, 4, 1, 3],next:'q28'},
    {t:'Ouvrez la fenêtre et laissez entrer le vent',d:[0, 3, 2, 5, 2, 3],next:'q36'},
    {t:'Fermez bien et allumez la lampe',d:[1, 3, 3, 4, 2, 2],next:'q34'},
    {t:'Je suis juste là pour faire nombre',d:[1, 1, 2, 3, 1, 2],next:'q31'},
  ]},
  q25:{id:'q25',q:'Quand monte la vapeur du thé, vous pensez à—',type:'Fumée du thé',opts:[
    {t:'De vieux amis autour du feu, peu de mots',d:[1, 3, 1, 3, 4, 1],next:'q29'},
    {t:'Être seul, propice à écrire',d:[0, 3, 3, 5, 1, 3],next:'q29'},
    {t:'La vie comme le thé : amère d\'abord',d:[2, 3, 3, 2, 4, 2],next:'q36'},
    {t:'Le thé refroidit et les gens se dispersent',d:[1, 4, 2, 3, 3, 2],next:'q35'},
    {t:'Trop bizarre',d:[1, 1, 2, 3, 1, 2],next:'q30'},
  ]},
  q26:{id:'q26',q:'En voyant les oies voler vers le sud, au fond—',type:'Oies du sud',opts:[
    {t:'La pensée du pays natal, sans la dire',d:[1, 4, 1, 3, 4, 2],next:'q34'},
    {t:'Le monde vaste, le moi petit',d:[1, 3, 4, 3, 2, 3],next:'q34'},
    {t:'L\'envie de les suivre et voir loin',d:[0, 3, 2, 4, 2, 4],next:'q35'},
    {t:'Casser un roseau pour l\'offrir au voyageur',d:[0, 4, 1, 3, 3, 2],next:'q36'},
    {t:'Aucune idée par où commencer',d:[1, 1, 2, 3, 1, 2],next:'q31'},
  ]},
  q27:{id:'q27',q:'La cloche du temple ancien — son écho dans la vallée. Vous—',type:'Cloche du temple',opts:[
    {t:'Écoutez mains jointes jusqu\'à la fin',d:[0, 3, 5, 4, 2, 2],next:'q35'},
    {t:'Vous souvenez d\'une phrase inachevée',d:[1, 4, 2, 3, 2, 4],next:'q35'},
    {t:'Partez sans troubler le silence',d:[1, 2, 3, 4, 2, 2],next:'q36'},
    {t:'Poussez la porte et empruntez un livre',d:[2, 3, 4, 3, 3, 3],next:'q34'},
    {t:'Aucune idée',d:[1, 1, 2, 3, 1, 2],next:'q30'},
  ]},
  q28:{id:'q28',q:'La lune filtrant par le papier, c\'est comme—',type:'Clair de lune',opts:[
    {t:'Une lettre jamais envoyée, pliée dans la manche',d:[1, 4, 1, 3, 2, 2],next:'q36'},
    {t:'D\'anciennes années soudain limpides',d:[1, 4, 2, 3, 3, 2],next:'q34'},
    {t:'Un petit chemin vers l\'inconnu',d:[0, 3, 3, 4, 1, 4],next:'q35'},
    {t:'Du mercure versé — lumière partout',d:[0, 4, 2, 3, 1, 5],next:'q36'},
    {t:'Esprit complètement vide',d:[1, 1, 2, 3, 1, 2],next:'q31'},
  ]},
  q29:{id:'q29',q:'Voulant confier votre cœur, au final vous—',type:'Secrets du cœur',opts:[
    {t:'L\'écrivez et le confiez au vent de printemps',d:[1, 4, 2, 3, 2, 4],next:'q34'},
    {t:'Le dites à un confident, en peu de mots',d:[1, 3, 1, 3, 4, 1],next:'q35'},
    {t:'Le ravalez en un long soupir',d:[2, 4, 2, 3, 3, 2],next:'q36'},
    {t:'Le dites aux monts et aux rivières — sans réponse',d:[0, 3, 4, 5, 2, 3],next:'q36'},
    {t:'De quoi parle-t-on ?',d:[1, 1, 2, 3, 1, 2],next:'q30'},
  ]},
  q30:{id:'q30',q:'Au milieu d\'un livre, soudain vous ne voulez plus lire—',type:'Détour · Pages',opts:[
    {t:'Le fermer et revenir un autre jour',d:[0, 3, 2, 4, 1, 3],next:'q14'},
    {t:'Sauter à la dernière page pour voir la fin',d:[1, 3, 1, 3, 2, 2],next:'q14'},
    {t:'Changer de livre — aucun ne sera fini',d:[1, 2, 2, 3, 1, 2],next:'q15'},
    {t:'Fixer la page de garde',d:[0, 3, 3, 5, 1, 2],next:'q15'},
    {t:'Fuir d\'abord, réfléchir après',d:[1, 1, 2, 3, 1, 2],next:'q14'},
  ]},
  q31:{id:'q31',q:'Dans l\'ascenseur avec quelqu\'un vu une fois—',type:'Détour · Rencontre',opts:[
    {t:'Faire semblant de regarder le téléphone',d:[1, 2, 1, 3, 0, 1],next:'q15'},
    {t:'Incliner légèrement la tête, tous deux silencieux',d:[0, 3, 2, 3, 2, 0],next:'q15'},
    {t:'Vouloir parler puis ravaler',d:[1, 3, 1, 2, 2, 1],next:'q16'},
    {t:'Se souvenir du nom mais feindre l\'inconnu',d:[1, 2, 2, 2, 1, 2],next:'q16'},
    {t:'Peu importe, n\'importe lequel',d:[1, 1, 2, 3, 1, 2],next:'q15'},
  ]},
  q32:{id:'q32',q:'Vous recevez un message sans contexte—',type:'Détour · Message',opts:[
    {t:'Le relire trois fois, devinant l\'expéditeur',d:[1, 2, 2, 2, 1, 1],next:'q18'},
    {t:'Ne pas répondre — attendre une explication',d:[1, 1, 1, 3, 1, 0],next:'q18'},
    {t:'Répondre par un point d\'interrogation',d:[2, 1, 1, 2, 0, 2],next:'q19'},
    {t:'Supposer une erreur et balayer',d:[1, 1, 0, 2, 1, 1],next:'q19'},
    {t:'Je suis juste là pour faire nombre',d:[1, 1, 2, 3, 1, 2],next:'q18'},
  ]},
  q33:{id:'q33',q:'Un vieux ticket glissé dans le carnet—',type:'Détour · Souvenir',opts:[
    {t:'Reconstituer ce jour par la date',d:[0, 3, 1, 2, 2, 1],next:'q19'},
    {t:'Le remettre et continuer autre chose',d:[1, 2, 2, 2, 1, 2],next:'q19'},
    {t:'Le jeter pour ne pas évoquer',d:[1, 2, 1, 2, 2, 0],next:'q20'},
    {t:'Le photographier puis oublier',d:[1, 2, 2, 3, 0, 2],next:'q20'},
    {t:'Trop bizarre',d:[1, 1, 2, 3, 1, 2],next:'q19'},
  ]},
  q34:{id:'q34',q:'Si vous ne pouviez laisser qu\'une ligne sur la garde—',type:'Question finale',opts:[
    {t:'« Il y a ici une vérité, mais les mots m\'échappent. »',d:[0, 3, 5, 5, 1, 2]},
    {t:'« L\'homme vit pour vivre. »',d:[2, 1, 0, 1, 3, 0]},
    {t:'« Big Brother is watching you »',d:[3, 0, 2, 1, 2, 2]},
    {t:'« So it goes. »',d:[2, 1, 2, 2, 1, 3]},
    {t:'Aucune idée par où commencer',d:[1, 1, 2, 3, 1, 2]},
  ],end:true},
  q35:{id:'q35',q:'Dernière question : comment aimeriez-vous être mal lu—',type:'Question finale',opts:[
    {t:'Qu\'on y lise de la chaleur dans le silence',d:[0, 4, 3, 4, 2, 3]},
    {t:'Qu\'on y lise une arête entre les mots',d:[4, 3, 3, 2, 3, 4]},
    {t:'Qu\'on y lise l\'artifice de la structure',d:[1, 2, 3, 2, 0, 3]},
    {t:'Qu\'on y lise de nouvelles possibilités dans l\'erreur',d:[1, 2, 3, 1, 0, 3]},
    {t:'Aucune idée',d:[1, 1, 2, 3, 1, 2]},
  ],end:true},
  q36:{id:'q36',q:'Dernière question : si la littérature est une fenêtre, vous voulez qu\'elle—',type:'Question finale',opts:[
    {t:'Montre les autres et vous-même',d:[2, 4, 2, 3, 4, 3]},
    {t:'Se balance au vent sans se fermer',d:[1, 4, 2, 4, 3, 4]},
    {t:'Ne s\'ouvre qu\'une fente — suffisant',d:[0, 3, 3, 5, 2, 2]},
    {t:'S\'ouvre grand et laisse entrer la pluie',d:[1, 3, 2, 3, 2, 4]},
    {t:'Esprit complètement vide',d:[1, 1, 2, 3, 1, 2]},
  ],end:true},
};
const LIT_START = 'q01';
