/* Literary temperament questions · pt */
const LIT_Q = {
  q01:{id:'q01',q:'Quando a chuva bate na janela à noite, você primeiro pensa em—',type:'Pensamento noturno',opts:[
    {t:'Cartas não enviadas e palavras não ditas',d:[1, 3, 1, 2, 2, 1],next:'q02'},
    {t:'Uma estrada antiga, uma figura que se afasta',d:[0, 3, 1, 2, 2, 0],next:'q03'},
    {t:'Quantas pessoas na cidade ainda estão acordadas',d:[2, 1, 2, 2, 3, 0],next:'q04'},
    {t:'A chuva em si, como um diálogo sem fim',d:[1, 2, 3, 2, 0, 2],next:'q05'},
    {t:'Muito estranho',d:[1, 1, 2, 3, 1, 2],next:'q30'},
  ]},
  q02:{id:'q02',q:'Se escrevesse meia frase deste humor, pararia em—',type:'Estado de espírito',opts:[
    {t:'«Então é assim.»',d:[2, 1, 2, 1, 1, 1],next:'q06'},
    {t:'«Que pena…»',d:[1, 3, 1, 2, 2, 0],next:'q07'},
    {t:'«Deixa estar.»',d:[1, 1, 1, 2, 2, 1],next:'q08'},
    {t:'«Espera — isso não bate.»',d:[2, 0, 3, 1, 0, 2],next:'q09'},
    {t:'Sem ideia por onde começar',d:[1, 1, 2, 3, 1, 2],next:'q31'},
  ]},
  q03:{id:'q03',q:'Ao entrar na multidão, você é mais como—',type:'Na multidão',opts:[
    {t:'Um observador frio que anota',d:[2, 1, 2, 2, 1, 1],next:'q06'},
    {t:'Alguém facilmente comovido ou ferido',d:[0, 3, 1, 1, 3, 0],next:'q07'},
    {t:'Um transeunte cortês e distante',d:[1, 2, 1, 3, 0, 1],next:'q08'},
    {t:'Quem tece histórias em segredo',d:[1, 2, 3, 2, 0, 2],next:'q09'},
    {t:'Sei lá',d:[1, 1, 2, 3, 1, 2],next:'q30'},
  ]},
  q04:{id:'q04',q:'Um bom livro interrompido no meio — você pensa—',type:'Notas de leitura',opts:[
    {t:'Preciso de um canto quieto para terminar',d:[1, 2, 1, 2, 1, 1],next:'q06'},
    {t:'Parar no suspense deixa gosto melhor',d:[1, 3, 1, 2, 0, 2],next:'q07'},
    {t:'O que aquele personagem está fazendo agora?',d:[0, 2, 2, 2, 2, 1],next:'q08'},
    {t:'Marcar esta página — voltarei',d:[2, 1, 3, 1, 1, 2],next:'q09'},
    {t:'Mente completamente vazia',d:[1, 1, 2, 3, 1, 2],next:'q31'},
  ]},
  q05:{id:'q05',q:'A palavra «saudade» evoca primeiro não um lugar, mas—',type:'Saudade',opts:[
    {t:'Um tom ao qual não se pode voltar',d:[0, 3, 1, 2, 2, 0],next:'q06'},
    {t:'Objetos, sons e cheiros antigos',d:[0, 3, 0, 1, 3, 0],next:'q07'},
    {t:'Seu eu jovem, brusco e sincero',d:[1, 2, 1, 2, 2, 1],next:'q08'},
    {t:'O tempo mesmo recuando',d:[1, 2, 3, 2, 1, 2],next:'q09'},
    {t:'Do que se trata?',d:[1, 1, 2, 3, 1, 2],next:'q30'},
  ]},
  q06:{id:'q06',q:'Qual silêncio você conhece melhor—',type:'Silêncio',opts:[
    {t:'Duas pessoas caladas, mas entendendo-se',d:[0, 2, 1, 2, 3, 0],next:'q10'},
    {t:'Esses segundos de lucidez no barulho',d:[1, 1, 2, 3, 0, 1],next:'q10'},
    {t:'O longo depois de engolir as palavras',d:[2, 2, 1, 2, 2, 0],next:'q30'},
    {t:'Querer falar e não achar a palavra exata',d:[1, 2, 3, 2, 0, 2],next:'q31'},
    {t:'Fugir primeiro, pensar depois',d:[1, 1, 2, 3, 1, 2],next:'q31'},
  ]},
  q07:{id:'q07',q:'Ao escrever, o primeiro a cair costuma ser—',type:'Na pena',opts:[
    {t:'Uma pergunta que não cede',d:[3, 0, 2, 0, 1, 1],next:'q11'},
    {t:'Uma cena concreta: janela, lâmpada, chuva',d:[0, 3, 1, 2, 1, 1],next:'q11'},
    {t:'Um verso sem começo nem fim',d:[0, 3, 2, 1, 1, 2],next:'q30'},
    {t:'Uma premissa estranha mas fascinante',d:[1, 1, 3, 1, 0, 3],next:'q31'},
    {t:'Tanto faz, qualquer um serve',d:[1, 1, 2, 3, 1, 2],next:'q30'},
  ]},
  q08:{id:'q08',q:'Quando a mágoa não cabe em palavras, você—',type:'Contenção',opts:[
    {t:'Escreve ou repassa em silêncio',d:[2, 2, 2, 2, 1, 2],next:'q12'},
    {t:'Finge que nada foi e segue o dia',d:[1, 1, 0, 1, 3, 0],next:'q12'},
    {t:'Se afasta até a emoção baixar',d:[0, 2, 1, 3, 1, 0],next:'q30'},
    {t:'Ri de repente para mudar o clima',d:[1, 1, 0, 2, 2, 2],next:'q31'},
    {t:'Só estou aqui de enfeite',d:[1, 1, 2, 3, 1, 2],next:'q31'},
  ]},
  q09:{id:'q09',q:'Qual luz relaxa você com mais facilidade—',type:'Luz',opts:[
    {t:'O crepúsculo, o céu entre claro e escuro',d:[0, 3, 1, 2, 1, 1],next:'q13'},
    {t:'A primeira luz na névoa da manhã',d:[0, 3, 1, 1, 2, 1],next:'q13'},
    {t:'O círculo quente de uma lâmpada à noite',d:[0, 2, 2, 3, 1, 1],next:'q30'},
    {t:'O branco do meio-dia, demasiado direto',d:[2, 1, 2, 1, 2, 2],next:'q31'},
    {t:'Muito estranho',d:[1, 1, 2, 3, 1, 2],next:'q30'},
  ]},
  q10:{id:'q10',q:'Se se comparasse a uma estação, estaria mais perto de—',type:'Estações',opts:[
    {t:'Fim da primavera: plenitude já com decadência',d:[1, 3, 1, 1, 2, 1],next:'q14'},
    {t:'Verão longo: úmido, interminável, relutante em ir',d:[2, 2, 2, 1, 1, 2],next:'q14'},
    {t:'Outono profundo: frio, claro, com olhar atrás',d:[1, 2, 2, 2, 2, 1],next:'q32'},
    {t:'Fim do inverno: duro, quieto, mas com renascimento',d:[2, 1, 3, 2, 1, 2],next:'q33'},
    {t:'Sem ideia por onde começar',d:[1, 1, 2, 3, 1, 2],next:'q31'},
  ]},
  q11:{id:'q11',q:'Ao ouvir uma catástrofe distante, sua primeira reação—',type:'Notícias distantes',opts:[
    {t:'Perguntar o porquê, não aceitar fácil',d:[3, 0, 2, 0, 2, 1],next:'q15'},
    {t:'Um aperto no peito que demora a ir embora',d:[1, 3, 1, 1, 3, 0],next:'q15'},
    {t:'Calar e encaixar os detalhes um a um',d:[2, 1, 2, 2, 2, 1],next:'q32'},
    {t:'Achar absurdo, sem poder rir',d:[2, 1, 3, 2, 1, 3],next:'q33'},
    {t:'Sei lá',d:[1, 1, 2, 3, 1, 2],next:'q30'},
  ]},
  q12:{id:'q12',q:'Uma boa história — por onde gostaria que começasse—',type:'Primeiro traço',opts:[
    {t:'Um caso menor que reflita toda uma era',d:[3, 1, 1, 1, 3, 0],next:'q16'},
    {t:'Um encontro casual onde o clima vem antes da trama',d:[1, 3, 1, 2, 1, 1],next:'q16'},
    {t:'Um enigma ou um detalhe fora do lugar',d:[1, 1, 3, 2, 0, 3],next:'q32'},
    {t:'O instante em que o cotidiano se racha',d:[2, 2, 1, 2, 2, 2],next:'q33'},
    {t:'Mente completamente vazia',d:[1, 1, 2, 3, 1, 2],next:'q31'},
  ]},
  q13:{id:'q13',q:'Ao se despedir de um amigo, você—',type:'Despedida',opts:[
    {t:'Diz pouco, mas olha mais uma vez',d:[1, 2, 1, 2, 2, 0],next:'q17'},
    {t:'Palavras leves para cobrir o peso',d:[1, 2, 0, 2, 2, 2],next:'q17'},
    {t:'Conta de repente algo sem relação',d:[1, 3, 1, 2, 1, 2],next:'q32'},
    {t:'Diz «adeus» como «até breve»',d:[0, 3, 1, 1, 2, 1],next:'q33'},
    {t:'Do que se trata?',d:[1, 1, 2, 3, 1, 2],next:'q30'},
  ]},
  q14:{id:'q14',q:'Ao acordar de um sonho, no travesseiro fica—',type:'Ao acordar',opts:[
    {t:'Uma emoção sem nome',d:[0, 3, 1, 2, 1, 2],next:'q18'},
    {t:'Uma imagem clara, como foto antiga',d:[0, 3, 1, 2, 2, 1],next:'q18'},
    {t:'Uma frase do sonho, ainda lembrada',d:[1, 2, 2, 2, 1, 2],next:'q22'},
    {t:'Só vazio, mas com sensação de perda',d:[1, 2, 3, 3, 0, 2],next:'q23'},
    {t:'Fugir primeiro, pensar depois',d:[1, 1, 2, 3, 1, 2],next:'q31'},
  ]},
  q15:{id:'q15',q:'Numa esquina onde a luz cai certa, você—',type:'Esquina',opts:[
    {t:'Para e olha gente e sombras',d:[1, 2, 1, 2, 1, 0],next:'q19'},
    {t:'Pensa em alguém antigo, alheio a este instante',d:[0, 3, 1, 2, 2, 0],next:'q19'},
    {t:'Tira o celular, temendo não captar o clima',d:[1, 2, 1, 3, 0, 1],next:'q22'},
    {t:'Sente que este momento não deve ser perturbado',d:[0, 2, 2, 3, 1, 1],next:'q23'},
    {t:'Tanto faz, qualquer um serve',d:[1, 1, 2, 3, 1, 2],next:'q30'},
  ]},
  q16:{id:'q16',q:'Seu primeiro instinto diante do «absurdo» é—',type:'O absurdo',opts:[
    {t:'O normal do mundo — não há de espantar',d:[2, 1, 2, 1, 2, 2],next:'q20'},
    {t:'Vazio sob uma superfície esplêndida',d:[2, 2, 1, 2, 1, 2],next:'q20'},
    {t:'Uma piada fria do destino',d:[1, 2, 2, 2, 1, 3],next:'q22'},
    {t:'Quem usa o absurdo como figueira',d:[3, 0, 2, 1, 2, 2],next:'q23'},
    {t:'Só estou aqui de enfeite',d:[1, 1, 2, 3, 1, 2],next:'q31'},
  ]},
  q17:{id:'q17',q:'Se tivesse de renunciar a uma coisa, menos soltaria—',type:'Escolha',opts:[
    {t:'A coragem de dizer a verdade',d:[3, 0, 2, 0, 2, 1],next:'q21'},
    {t:'A sensibilidade e o apego à beleza',d:[0, 3, 2, 1, 1, 2],next:'q21'},
    {t:'Os laços com uns poucos escolhidos',d:[0, 2, 0, 1, 4, 0],next:'q24'},
    {t:'Espaço para pensar por si',d:[2, 1, 3, 2, 0, 2],next:'q25'},
    {t:'Muito estranho',d:[1, 1, 2, 3, 1, 2],next:'q30'},
  ]},
  q18:{id:'q18',q:'Na solidão, o que mais gosta é—',type:'Solidão',opts:[
    {t:'Não fazer nada, deixar o tempo passar',d:[0, 2, 2, 3, 1, 0],next:'q22'},
    {t:'Ler, ouvir o vento, falar consigo',d:[1, 2, 3, 2, 1, 1],next:'q22'},
    {t:'Ordenar os dias pequenos',d:[2, 0, 1, 1, 2, 0],next:'q26'},
    {t:'Deixar a mente vagar e anotar ideias',d:[1, 2, 3, 2, 0, 3],next:'q27'},
    {t:'Sem ideia por onde começar',d:[1, 1, 2, 3, 1, 2],next:'q31'},
  ]},
  q19:{id:'q19',q:'Se só pudesse ficar com falar ou escrever—',type:'Expressão',opts:[
    {t:'Escrever. Ao falar, as palavras distorcem',d:[1, 2, 2, 2, 1, 2],next:'q23'},
    {t:'Falar. Escrever é lento para o batimento',d:[0, 3, 1, 1, 2, 1],next:'q23'},
    {t:'Pouco de ambos — o silêncio é mais honesto',d:[1, 1, 2, 3, 1, 1],next:'q26'},
    {t:'Outro caminho: desenhar, caminhar ou só ver',d:[1, 2, 3, 2, 0, 2],next:'q27'},
    {t:'Sei lá',d:[1, 1, 2, 3, 1, 2],next:'q30'},
  ]},
  q20:{id:'q20',q:'Que tipo de frase comove você mais facilmente?',type:'Gosto literário',opts:[
    {t:'Direta, afiada, com uma ponta',d:[3, 0, 1, 1, 1, 2],next:'q24'},
    {t:'Serena, densa, como um plano longo',d:[1, 3, 1, 0, 3, 0],next:'q24'},
    {t:'Fria, bela, com um pouco de distância',d:[2, 2, 1, 3, 0, 1],next:'q28'},
    {t:'Abstrata, saltitante, que faz pensar',d:[1, 1, 3, 2, 0, 3],next:'q29'},
    {t:'Mente completamente vazia',d:[1, 1, 2, 3, 1, 2],next:'q31'},
  ]},
  q21:{id:'q21',q:'Numa equipe, você costuma ser—',type:'Colaboração',opts:[
    {t:'Quem aponta os problemas',d:[3, 0, 1, 0, 1, 1],next:'q25'},
    {t:'Quem suaviza o clima',d:[0, 2, 0, 1, 3, 0],next:'q25'},
    {t:'Quem trabalha em silêncio',d:[1, 0, 0, 1, 2, 0],next:'q28'},
    {t:'Quem propõe ideias estranhas',d:[1, 2, 2, 1, 0, 3],next:'q29'},
    {t:'Do que se trata?',d:[1, 1, 2, 3, 1, 2],next:'q30'},
  ]},
  q22:{id:'q22',q:'Numa tarde vazia, você primeiro nota—',type:'Tarde vazia',opts:[
    {t:'A luz movendo-se devagar no chão',d:[0, 2, 2, 3, 1, 1],next:'q26'},
    {t:'Ruídos distantes e tenues da cidade',d:[1, 2, 1, 2, 2, 0],next:'q26'},
    {t:'O que ainda não terminou',d:[2, 1, 2, 2, 2, 1],next:'q34'},
    {t:'O tempo que de repente fica lento',d:[1, 2, 3, 2, 1, 2],next:'q35'},
    {t:'Fugir primeiro, pensar depois',d:[1, 1, 2, 3, 1, 2],next:'q31'},
  ]},
  q23:{id:'q23',q:'Junto à estrada antiga há uma acácia velha — você—',type:'Estrada antiga',opts:[
    {t:'Descansa sob ela, ouvindo o vento contar',d:[0, 3, 2, 4, 3, 2],next:'q27'},
    {t:'Dobra uma folha em manuscritos inacabados',d:[1, 4, 2, 3, 2, 4],next:'q27'},
    {t:'Lembra uma despedida e para muito tempo',d:[1, 4, 1, 3, 3, 2],next:'q34'},
    {t:'Segue caminhando sem olhar atrás',d:[3, 2, 2, 2, 4, 2],next:'q35'},
    {t:'Tanto faz, qualquer um serve',d:[1, 1, 2, 3, 1, 2],next:'q30'},
  ]},
  q24:{id:'q24',q:'O papel da janela move-se ao vento, como página não lida. Você—',type:'Papel na janela',opts:[
    {t:'Segura-o, temendo que voe',d:[1, 4, 1, 3, 2, 2],next:'q28'},
    {t:'Deixa-o farfalhar como fundo',d:[0, 3, 3, 4, 1, 3],next:'q28'},
    {t:'Abre a janela e deixa entrar o vento',d:[0, 3, 2, 5, 2, 3],next:'q36'},
    {t:'Fecha bem e acende a lâmpada',d:[1, 3, 3, 4, 2, 2],next:'q34'},
    {t:'Só estou aqui de enfeite',d:[1, 1, 2, 3, 1, 2],next:'q31'},
  ]},
  q25:{id:'q25',q:'Quando sobe o vapor do chá, você pensa em—',type:'Fumaça do chá',opts:[
    {t:'Velhos amigos junto ao fogo, poucas palavras',d:[1, 3, 1, 3, 4, 1],next:'q29'},
    {t:'Sentar-se só, ideal para escrever',d:[0, 3, 3, 5, 1, 3],next:'q29'},
    {t:'A vida como chá: amarga primeiro',d:[2, 3, 3, 2, 4, 2],next:'q36'},
    {t:'O chá esfria e a gente se dispersa',d:[1, 4, 2, 3, 3, 2],next:'q35'},
    {t:'Muito estranho',d:[1, 1, 2, 3, 1, 2],next:'q30'},
  ]},
  q26:{id:'q26',q:'Ao ver gansos voar para o sul, no fundo—',type:'Gansos do sul',opts:[
    {t:'Saudade da pátria, sem dizer',d:[1, 4, 1, 3, 4, 2],next:'q34'},
    {t:'O mundo vasto, o eu pequeno',d:[1, 3, 4, 3, 2, 3],next:'q34'},
    {t:'Vontade de ir com eles e ver longe',d:[0, 3, 2, 4, 2, 4],next:'q35'},
    {t:'Quebrar um junco para dar ao caminhante',d:[0, 4, 1, 3, 3, 2],next:'q36'},
    {t:'Sem ideia por onde começar',d:[1, 1, 2, 3, 1, 2],next:'q31'},
  ]},
  q27:{id:'q27',q:'O sino do templo antigo — seu eco no vale. Você—',type:'Sino do templo',opts:[
    {t:'Escuta de mãos juntas até cessar',d:[0, 3, 5, 4, 2, 2],next:'q35'},
    {t:'Lembra uma frase que não terminou',d:[1, 4, 2, 3, 2, 4],next:'q35'},
    {t:'Vai embora sem perturbar a quietude',d:[1, 2, 3, 4, 2, 2],next:'q36'},
    {t:'Empurra o portão e pede um livro',d:[2, 3, 4, 3, 3, 3],next:'q34'},
    {t:'Sei lá',d:[1, 1, 2, 3, 1, 2],next:'q30'},
  ]},
  q28:{id:'q28',q:'A lua filtrando-se pelo papel, é como—',type:'Claro de lua',opts:[
    {t:'Uma carta não enviada, dobrada na manga',d:[1, 4, 1, 3, 2, 2],next:'q36'},
    {t:'Anos velhos que de repente se aclaram',d:[1, 4, 2, 3, 3, 2],next:'q34'},
    {t:'Um caminho pequeno para o desconhecido',d:[0, 3, 3, 4, 1, 4],next:'q35'},
    {t:'Mercúrio derramado — luz por toda parte',d:[0, 4, 2, 3, 1, 5],next:'q36'},
    {t:'Mente completamente vazia',d:[1, 1, 2, 3, 1, 2],next:'q31'},
  ]},
  q29:{id:'q29',q:'Querendo contar o coração a alguém, no fim—',type:'Segredos do coração',opts:[
    {t:'Escreve e entrega ao vento da primavera',d:[1, 4, 2, 3, 2, 4],next:'q34'},
    {t:'Diz a um confidente, em poucas palavras',d:[1, 3, 1, 3, 4, 1],next:'q35'},
    {t:'Engole e fica um suspiro longo',d:[2, 4, 2, 3, 3, 2],next:'q36'},
    {t:'Diz a montes e rios — sem resposta',d:[0, 3, 4, 5, 2, 3],next:'q36'},
    {t:'Do que se trata?',d:[1, 1, 2, 3, 1, 2],next:'q30'},
  ]},
  q30:{id:'q30',q:'No meio de um livro, de repente não quer ler—',type:'Desvio · Páginas',opts:[
    {t:'Fecha e volta outro dia',d:[0, 3, 2, 4, 1, 3],next:'q14'},
    {t:'Pula à última página para espiar o fim',d:[1, 3, 1, 3, 2, 2],next:'q14'},
    {t:'Troca de livro — nenhum se acabará',d:[1, 2, 2, 3, 1, 2],next:'q15'},
    {t:'Olha fixamente a guarda',d:[0, 3, 3, 5, 1, 2],next:'q15'},
    {t:'Fugir primeiro, pensar depois',d:[1, 1, 2, 3, 1, 2],next:'q14'},
  ]},
  q31:{id:'q31',q:'No elevador com alguém visto uma vez—',type:'Desvio · Encontro',opts:[
    {t:'Finge olhar o celular',d:[1, 2, 1, 3, 0, 1],next:'q15'},
    {t:'Acena levemente, ambos em silêncio',d:[0, 3, 2, 3, 2, 0],next:'q15'},
    {t:'Quer dizer algo e engole',d:[1, 3, 1, 2, 2, 1],next:'q16'},
    {t:'Lembra o nome mas age como estranho',d:[1, 2, 2, 2, 1, 2],next:'q16'},
    {t:'Tanto faz, qualquer um serve',d:[1, 1, 2, 3, 1, 2],next:'q15'},
  ]},
  q32:{id:'q32',q:'Recebe uma mensagem sem contexto—',type:'Desvio · Mensagem',opts:[
    {t:'Lê três vezes, adivinhando quem é',d:[1, 2, 2, 2, 1, 1],next:'q18'},
    {t:'Não responde — espera explicação',d:[1, 1, 1, 3, 1, 0],next:'q18'},
    {t:'Responde com ponto de interrogação',d:[2, 1, 1, 2, 0, 2],next:'q19'},
    {t:'Supõe erro e desliza',d:[1, 1, 0, 2, 1, 1],next:'q19'},
    {t:'Só estou aqui de enfeite',d:[1, 1, 2, 3, 1, 2],next:'q18'},
  ]},
  q33:{id:'q33',q:'Na caderneta há um ticket velho—',type:'Desvio · Lembrança',opts:[
    {t:'Reconstrói aquele dia pela data',d:[0, 3, 1, 2, 2, 1],next:'q19'},
    {t:'Guarda de novo e segue escrevendo',d:[1, 2, 2, 2, 1, 2],next:'q19'},
    {t:'Joga fora para não evocar',d:[1, 2, 1, 2, 2, 0],next:'q20'},
    {t:'Fotografa e depois esquece',d:[1, 2, 2, 3, 0, 2],next:'q20'},
    {t:'Muito estranho',d:[1, 1, 2, 3, 1, 2],next:'q19'},
  ]},
  q34:{id:'q34',q:'Se só pudesse deixar uma linha na guarda—',type:'Pergunta final',opts:[
    {t:'«Há verdade aqui, mas ao querer dizer, perde-se.»',d:[0, 3, 5, 5, 1, 2]},
    {t:'«O homem vive para viver.»',d:[2, 1, 0, 1, 3, 0]},
    {t:'«Big Brother is watching you»',d:[3, 0, 2, 1, 2, 2]},
    {t:'«So it goes.»',d:[2, 1, 2, 2, 1, 3]},
    {t:'Sem ideia por onde começar',d:[1, 1, 2, 3, 1, 2]},
  ],end:true},
  q35:{id:'q35',q:'Última pergunta: como gostaria de ser mal lido—',type:'Pergunta final',opts:[
    {t:'Que leiam calor no silêncio',d:[0, 4, 3, 4, 2, 3]},
    {t:'Que leiam fio entre as palavras',d:[4, 3, 3, 2, 3, 4]},
    {t:'Que leiam artifício na estrutura',d:[1, 2, 3, 2, 0, 3]},
    {t:'Que leiam novas possibilidades no erro',d:[1, 2, 3, 1, 0, 3]},
    {t:'Sei lá',d:[1, 1, 2, 3, 1, 2]},
  ],end:true},
  q36:{id:'q36',q:'Última pergunta: se a literatura é uma janela, quer que—',type:'Pergunta final',opts:[
    {t:'Mostre outros e a si mesmo',d:[2, 4, 2, 3, 4, 3]},
    {t:'Balance ao vento sem fechar',d:[1, 4, 2, 4, 3, 4]},
    {t:'Abra só um pouco — basta',d:[0, 3, 3, 5, 2, 2]},
    {t:'Abra de par em par e entre a chuva',d:[1, 3, 2, 3, 2, 4]},
    {t:'Mente completamente vazia',d:[1, 1, 2, 3, 1, 2]},
  ],end:true},
};
const LIT_START = 'q01';
