/* Literary temperament questions · es */
const LIT_Q = {
  q01:{id:'q01',q:'Cuando la lluvia golpea la ventana de noche, lo primero que piensas suele ser—',type:'Pensamiento nocturno',opts:[
    {t:'Cartas no enviadas y palabras no dichas',d:[1, 3, 1, 1, 2, 1],next:'q02'},
    {t:'Un camino antiguo, una figura que se aleja',d:[0, 3, 1, 1, 2, 0],next:'q03'},
    {t:'Cuánta gente en la ciudad sigue despierta',d:[2, 1, 2, 1, 3, 0],next:'q04'},
    {t:'La lluvia misma, como un diálogo sin final',d:[1, 2, 3, 1, 0, 2],next:'q05'},
    {t:'Qué raro',d:[2, 1, 1, 1, 1, 1],next:'q30'},
  ]},
  q02:{id:'q02',q:'Si escribieras media frase de este ánimo, se detendría en—',type:'Estado de ánimo',opts:[
    {t:'«Así es.»',d:[2, 1, 2, 1, 1, 1],next:'q06'},
    {t:'«Qué lástima…»',d:[1, 3, 1, 1, 2, 0],next:'q07'},
    {t:'«Que sea.»',d:[1, 1, 1, 1, 2, 1],next:'q08'},
    {t:'«Espera, esto no cuadra.»',d:[2, 0, 3, 1, 0, 2],next:'q09'},
    {t:'Sin idea por dónde empezar',d:[2, 1, 1, 1, 1, 1],next:'q31'},
  ]},
  q03:{id:'q03',q:'Al entrar en la multitud, eres más como—',type:'Entre la multitud',opts:[
    {t:'Un observador frío que anota',d:[2, 1, 2, 1, 1, 1],next:'q06'},
    {t:'Alguien fácilmente conmovido o herido',d:[0, 3, 1, 1, 3, 0],next:'q07'},
    {t:'Un transeúnte cortés y distante',d:[1, 2, 1, 2, 0, 1],next:'q08'},
    {t:'Quien teje historias en secreto',d:[1, 2, 3, 1, 0, 2],next:'q09'},
    {t:'Ni idea',d:[2, 1, 1, 1, 1, 1],next:'q30'},
  ]},
  q04:{id:'q04',q:'Si interrumpen un buen libro a mitad, piensas—',type:'Notas de lectura',opts:[
    {t:'Hay que buscar un rincón tranquilo para acabarlo',d:[1, 2, 1, 1, 1, 1],next:'q06'},
    {t:'Parar en el suspense deja mejor sabor',d:[1, 3, 1, 1, 0, 2],next:'q07'},
    {t:'¿Qué estará haciendo ahora ese personaje?',d:[0, 2, 2, 1, 2, 1],next:'q08'},
    {t:'Marcar esta página: volveré',d:[2, 1, 3, 1, 1, 2],next:'q09'},
    {t:'Mente en blanco',d:[2, 1, 1, 1, 1, 1],next:'q31'},
  ]},
  q05:{id:'q05',q:'La palabra «nostalgia» evoca primero no un lugar, sino—',type:'Nostalgia',opts:[
    {t:'Un tono al que ya no se puede volver',d:[0, 3, 1, 1, 2, 0],next:'q06'},
    {t:'Objetos, sonidos y olores viejos',d:[0, 3, 0, 1, 3, 0],next:'q07'},
    {t:'Tu yo adolescente, brusco y sincero',d:[1, 2, 1, 1, 2, 1],next:'q08'},
    {t:'El tiempo mismo retrocediendo',d:[1, 2, 3, 1, 1, 2],next:'q09'},
    {t:'¿De qué va esto?',d:[2, 1, 1, 1, 1, 1],next:'q30'},
  ]},
  q06:{id:'q06',q:'¿Qué silencio conoces mejor—',type:'Silencio',opts:[
    {t:'Dos personas calladas, pero entendiéndose',d:[0, 2, 1, 1, 3, 0],next:'q10'},
    {t:'Esos segundos de lucidez en un lugar ruidoso',d:[1, 1, 2, 2, 0, 1],next:'q10'},
    {t:'Lo largo que queda tras tragarse las palabras',d:[2, 2, 1, 1, 2, 0],next:'q30'},
    {t:'Querer hablar y no hallar la palabra exacta',d:[1, 2, 3, 1, 0, 2],next:'q31'},
    {t:'Huir primero, pensar después',d:[2, 1, 1, 1, 1, 1],next:'q31'},
  ]},
  q07:{id:'q07',q:'Al escribir, lo primero que cae suele ser—',type:'En la pluma',opts:[
    {t:'Una pregunta que no cede',d:[3, 0, 2, 0, 1, 1],next:'q11'},
    {t:'Una escena concreta: ventana, lámpara, lluvia',d:[0, 3, 1, 1, 1, 1],next:'q11'},
    {t:'Un verso sin principio ni fin',d:[0, 3, 2, 1, 1, 2],next:'q30'},
    {t:'Una premisa extraña pero fascinante',d:[1, 1, 3, 1, 0, 3],next:'q31'},
    {t:'Lo que sea, da igual',d:[2, 1, 1, 1, 1, 1],next:'q30'},
  ]},
  q08:{id:'q08',q:'Cuando la injusticia no cabe en palabras, sueles—',type:'Contención',opts:[
    {t:'Escribirla o repasarla en silencio',d:[2, 2, 2, 1, 1, 2],next:'q12'},
    {t:'Fingir que nada pasa y seguir el día',d:[1, 1, 0, 1, 3, 0],next:'q12'},
    {t:'Alejarte de la gente hasta que baje',d:[0, 2, 1, 2, 1, 0],next:'q30'},
    {t:'Reír de pronto para cambiar el ambiente',d:[1, 1, 0, 1, 2, 2],next:'q31'},
    {t:'Solo vengo de relleno',d:[2, 1, 1, 1, 1, 1],next:'q31'},
  ]},
  q09:{id:'q09',q:'¿Qué luz te relaja con más facilidad—',type:'Luz',opts:[
    {t:'El crepúsculo, el cielo entre claro y oscuro',d:[0, 3, 1, 1, 1, 1],next:'q13'},
    {t:'La primera luz entre la niebla matinal',d:[0, 3, 1, 1, 2, 1],next:'q13'},
    {t:'El círculo cálido de una lámpara nocturna',d:[0, 2, 2, 2, 1, 1],next:'q30'},
    {t:'El blanco del mediodía, demasiado directo',d:[2, 1, 2, 1, 2, 2],next:'q31'},
    {t:'Qué raro',d:[2, 1, 1, 1, 1, 1],next:'q30'},
  ]},
  q10:{id:'q10',q:'Si te compararas con una estación, estarías más cerca de—',type:'Estaciones',opts:[
    {t:'Finales de primavera: plenitud ya con decadencia',d:[1, 3, 1, 1, 2, 1],next:'q14'},
    {t:'Verano largo: húmedo, interminable, renuente a irse',d:[2, 2, 2, 1, 1, 2],next:'q14'},
    {t:'Otoño profundo: frío, claro, con mirada atrás',d:[1, 2, 2, 1, 2, 1],next:'q32'},
    {t:'Invierno tardío: duro, quieto, pero con renacer',d:[2, 1, 3, 1, 1, 2],next:'q33'},
    {t:'Sin idea por dónde empezar',d:[2, 1, 1, 1, 1, 1],next:'q31'},
  ]},
  q11:{id:'q11',q:'Al oír una catástrofe lejana, tu primera reacción es más—',type:'Noticias lejanas',opts:[
    {t:'Preguntar el porqué, no aceptar fácil',d:[3, 0, 2, 0, 2, 1],next:'q15'},
    {t:'Un nudo en el pecho que tarda en irse',d:[1, 3, 1, 1, 3, 0],next:'q15'},
    {t:'Callar y encajar los detalles uno a uno',d:[2, 1, 2, 1, 2, 1],next:'q32'},
    {t:'Encontrarlo absurdo, sin poder reírse',d:[2, 1, 3, 1, 1, 3],next:'q33'},
    {t:'Ni idea',d:[2, 1, 1, 1, 1, 1],next:'q30'},
  ]},
  q12:{id:'q12',q:'Una buena historia — ¿por dónde querrías que empezara—',type:'Primer trazo',opts:[
    {t:'Un asunto menor que refleje toda una época',d:[3, 1, 1, 1, 3, 0],next:'q16'},
    {t:'Un encuentro casual donde el clima va antes que la trama',d:[1, 3, 1, 1, 1, 1],next:'q16'},
    {t:'Un acertijo o un detalle fuera de lugar',d:[1, 1, 3, 1, 0, 3],next:'q32'},
    {t:'El instante en que lo cotidiano se resquebraja',d:[2, 2, 1, 1, 2, 2],next:'q33'},
    {t:'Mente en blanco',d:[2, 1, 1, 1, 1, 1],next:'q31'},
  ]},
  q13:{id:'q13',q:'Al despedirte de un amigo, sueles decir o hacer—',type:'Despedida',opts:[
    {t:'Poco, pero mirar una vez más',d:[1, 2, 1, 1, 2, 0],next:'q17'},
    {t:'Palabras ligeras para cubrir lo pesado',d:[1, 2, 0, 1, 2, 2],next:'q17'},
    {t:'Contar de pronto algo sin relación',d:[1, 3, 1, 1, 1, 2],next:'q32'},
    {t:'Decir «adiós» como «hasta pronto»',d:[0, 3, 1, 1, 2, 1],next:'q33'},
    {t:'¿De qué va esto?',d:[2, 1, 1, 1, 1, 1],next:'q30'},
  ]},
  q14:{id:'q14',q:'Al despertar de un sueño, en la almohada queda a menudo—',type:'Al despertar',opts:[
    {t:'Una emoción sin nombre',d:[0, 3, 1, 1, 1, 2],next:'q18'},
    {t:'Una imagen clara, como foto antigua',d:[0, 3, 1, 1, 2, 1],next:'q18'},
    {t:'Una frase del sueño, aún recordada',d:[1, 2, 2, 1, 1, 2],next:'q22'},
    {t:'Solo vacío, pero con sensación de pérdida',d:[1, 2, 3, 2, 0, 2],next:'q23'},
    {t:'Huir primero, pensar después',d:[2, 1, 1, 1, 1, 1],next:'q31'},
  ]},
  q15:{id:'q15',q:'En una esquina donde la luz cae justo, tú—',type:'Esquina',opts:[
    {t:'Te detienes a mirar gente y sombras',d:[1, 2, 1, 1, 1, 0],next:'q19'},
    {t:'Piensas en alguien antiguo, ajeno a este instante',d:[0, 3, 1, 1, 2, 0],next:'q19'},
    {t:'Sacas el móvil, temiendo no captar el ambiente',d:[1, 2, 1, 2, 0, 1],next:'q22'},
    {t:'Sientes que este momento no debe interrumpirse',d:[0, 2, 2, 2, 1, 1],next:'q23'},
    {t:'Lo que sea, da igual',d:[2, 1, 1, 1, 1, 1],next:'q30'},
  ]},
  q16:{id:'q16',q:'Tu primer instinto ante «lo absurdo» es—',type:'Lo absurdo',opts:[
    {t:'Lo normal del mundo — no hay que asombrarse',d:[2, 1, 2, 1, 2, 2],next:'q20'},
    {t:'Vacío bajo una superficie espléndida',d:[2, 2, 1, 1, 1, 2],next:'q20'},
    {t:'Un chiste frío del destino',d:[1, 2, 2, 1, 1, 3],next:'q22'},
    {t:'Quien usa lo absurdo como hoja de parra',d:[3, 0, 2, 1, 2, 2],next:'q23'},
    {t:'Solo vengo de relleno',d:[2, 1, 1, 1, 1, 1],next:'q31'},
  ]},
  q17:{id:'q17',q:'Si tuvieras que renunciar a una cosa, menos soltarías—',type:'Elección',opts:[
    {t:'El valor de decir la verdad',d:[3, 0, 2, 0, 2, 1],next:'q21'},
    {t:'La sensibilidad y el apego a la belleza',d:[0, 3, 2, 1, 1, 2],next:'q21'},
    {t:'Los lazos con unos pocos elegidos',d:[0, 2, 0, 1, 4, 0],next:'q24'},
    {t:'Espacio para pensar por ti mismo',d:[2, 1, 3, 1, 0, 2],next:'q25'},
    {t:'Qué raro',d:[2, 1, 1, 1, 1, 1],next:'q30'},
  ]},
  q18:{id:'q18',q:'En soledad, lo que más disfrutas es—',type:'Soledad',opts:[
    {t:'No hacer nada, dejar pasar el tiempo',d:[0, 2, 2, 2, 1, 0],next:'q22'},
    {t:'Leer, escuchar el viento, hablar contigo',d:[1, 2, 3, 1, 1, 1],next:'q22'},
    {t:'Ordenar los días pequeños',d:[2, 0, 1, 1, 2, 0],next:'q26'},
    {t:'Dejar vagar la mente y anotar ideas sueltas',d:[1, 2, 3, 1, 0, 3],next:'q27'},
    {t:'Sin idea por dónde empezar',d:[2, 1, 1, 1, 1, 1],next:'q31'},
  ]},
  q19:{id:'q19',q:'Si solo pudieras quedarte con hablar o escribir—',type:'Expresión',opts:[
    {t:'Escribir. Al hablar, las palabras se distorsionan',d:[1, 2, 2, 1, 1, 2],next:'q23'},
    {t:'Hablar. Escribir es lento para el latido',d:[0, 3, 1, 1, 2, 1],next:'q23'},
    {t:'Poco de ambos — el silencio es más honesto',d:[1, 1, 2, 2, 1, 1],next:'q26'},
    {t:'Otra vía: dibujar, caminar o solo mirar',d:[1, 2, 3, 1, 0, 2],next:'q27'},
    {t:'Ni idea',d:[2, 1, 1, 1, 1, 1],next:'q30'},
  ]},
  q20:{id:'q20',q:'¿Qué tipo de frase te conmueve más fácilmente?',type:'Gusto literario',opts:[
    {t:'Directa, afilada, con una punta',d:[3, 0, 1, 1, 1, 2],next:'q24'},
    {t:'Serena, densa, como un plano largo',d:[1, 3, 1, 0, 3, 0],next:'q24'},
    {t:'Fría, bella, con un poco de distancia',d:[2, 2, 1, 2, 0, 1],next:'q28'},
    {t:'Abstracta, saltarina, que hace pensar',d:[1, 1, 3, 1, 0, 3],next:'q29'},
    {t:'Mente en blanco',d:[2, 1, 1, 1, 1, 1],next:'q31'},
  ]},
  q21:{id:'q21',q:'En un equipo, sueles ser—',type:'Colaboración',opts:[
    {t:'Quien señala los problemas',d:[3, 0, 1, 0, 1, 1],next:'q25'},
    {t:'Quien suaviza el ambiente',d:[0, 2, 0, 1, 3, 0],next:'q25'},
    {t:'Quien trabaja en silencio',d:[1, 0, 0, 1, 2, 0],next:'q28'},
    {t:'Quien propone ideas raras',d:[1, 2, 2, 1, 0, 3],next:'q29'},
    {t:'¿De qué va esto?',d:[2, 1, 1, 1, 1, 1],next:'q30'},
  ]},
  q22:{id:'q22',q:'En una tarde vacía, lo primero que notas es—',type:'Tarde vacía',opts:[
    {t:'La luz moviéndose lento por el suelo',d:[0, 2, 2, 2, 1, 1],next:'q26'},
    {t:'Ruidos lejanos y tenues de la ciudad',d:[1, 2, 1, 1, 2, 0],next:'q26'},
    {t:'Lo que aún no has terminado',d:[2, 1, 2, 1, 2, 1],next:'q34'},
    {t:'El tiempo que de pronto se vuelve lento',d:[1, 2, 3, 1, 1, 2],next:'q35'},
    {t:'Huir primero, pensar después',d:[2, 1, 1, 1, 1, 1],next:'q31'},
  ]},
  q23:{id:'q23',q:'Junto al camino antiguo hay un soplo viejo — tú—',type:'Camino antiguo',opts:[
    {t:'Descansas bajo él, oyendo al viento contar',d:[0, 3, 2, 3, 3, 2],next:'q27'},
    {t:'Doblas una hoja en manuscritos sin acabar',d:[1, 4, 2, 2, 2, 4],next:'q27'},
    {t:'Recuerdas una despedida y te detienes mucho',d:[1, 4, 1, 2, 3, 2],next:'q34'},
    {t:'Sigues caminando sin mirar atrás',d:[3, 2, 2, 1, 4, 2],next:'q35'},
    {t:'Lo que sea, da igual',d:[2, 1, 1, 1, 1, 1],next:'q30'},
  ]},
  q24:{id:'q24',q:'El papel de la ventana se mueve al viento, como una página no leída. Tú—',type:'Papel en la ventana',opts:[
    {t:'Lo sujetas, temiendo que vuele',d:[1, 4, 1, 2, 2, 2],next:'q28'},
    {t:'Lo dejas crujir como fondo',d:[0, 3, 3, 3, 1, 3],next:'q28'},
    {t:'Abres la ventana y dejas entrar el viento',d:[0, 3, 2, 4, 2, 3],next:'q36'},
    {t:'Cierras bien y enciendes la lámpara',d:[1, 3, 3, 3, 2, 2],next:'q34'},
    {t:'Solo vengo de relleno',d:[2, 1, 1, 1, 1, 1],next:'q31'},
  ]},
  q25:{id:'q25',q:'Cuando sube el humo del té, piensas en—',type:'Humo del té',opts:[
    {t:'Viejos amigos junto al fuego, pocas palabras',d:[1, 3, 1, 2, 4, 1],next:'q29'},
    {t:'Sentarte solo, ideal para escribir',d:[0, 3, 3, 4, 1, 3],next:'q29'},
    {t:'La vida como té: amarga al principio',d:[2, 3, 3, 1, 4, 2],next:'q36'},
    {t:'El té se enfría y la gente se dispersa',d:[1, 4, 2, 2, 3, 2],next:'q35'},
    {t:'Qué raro',d:[2, 1, 1, 1, 1, 1],next:'q30'},
  ]},
  q26:{id:'q26',q:'Al ver gansos volar al sur, en el fondo sientes—',type:'Gansos del sur',opts:[
    {t:'Añoranza de la patria, sin decirla',d:[1, 4, 1, 2, 4, 2],next:'q34'},
    {t:'El mundo vasto, el yo pequeño',d:[1, 3, 4, 2, 2, 3],next:'q34'},
    {t:'Ganas de ir con ellos y ver lejos',d:[0, 3, 2, 3, 2, 4],next:'q35'},
    {t:'Romper un junco para regalar al caminante',d:[0, 4, 1, 2, 3, 2],next:'q36'},
    {t:'Sin idea por dónde empezar',d:[2, 1, 1, 1, 1, 1],next:'q31'},
  ]},
  q27:{id:'q27',q:'La campana del templo antiguo — su eco en el valle. Tú—',type:'Campana del templo',opts:[
    {t:'Escuchas con manos juntas hasta que cesa',d:[0, 3, 5, 3, 2, 2],next:'q35'},
    {t:'Recuerdas una frase que no terminaste',d:[1, 4, 2, 2, 2, 4],next:'q35'},
    {t:'Te vas, sin perturbar la quietud',d:[1, 2, 3, 3, 2, 2],next:'q36'},
    {t:'Empujas la puerta y pides un libro',d:[2, 3, 4, 2, 3, 3],next:'q34'},
    {t:'Ni idea',d:[2, 1, 1, 1, 1, 1],next:'q30'},
  ]},
  q28:{id:'q28',q:'La luna filtrándose por el papel, es como—',type:'Claro de luna',opts:[
    {t:'Una carta no enviada, doblada en la manga',d:[1, 4, 1, 2, 2, 2],next:'q36'},
    {t:'Años viejos que de pronto se aclaran',d:[1, 4, 2, 2, 3, 2],next:'q34'},
    {t:'Un sendero pequeño hacia lo desconocido',d:[0, 3, 3, 3, 1, 4],next:'q35'},
    {t:'Mercurio derramado — luz por doquier',d:[0, 4, 2, 2, 1, 5],next:'q36'},
    {t:'Mente en blanco',d:[2, 1, 1, 1, 1, 1],next:'q31'},
  ]},
  q29:{id:'q29',q:'Queriendo contar tu corazón a alguien, al final—',type:'Secretos del corazón',opts:[
    {t:'Lo escribes y se lo das al viento de primavera',d:[1, 4, 2, 2, 2, 4],next:'q34'},
    {t:'Se lo dices a un confidente, en pocas palabras',d:[1, 3, 1, 2, 4, 1],next:'q35'},
    {t:'Lo tragas y queda un suspiro largo',d:[2, 4, 2, 2, 3, 2],next:'q36'},
    {t:'Se lo dices a montes y ríos — sin respuesta',d:[0, 3, 4, 4, 2, 3],next:'q36'},
    {t:'¿De qué va esto?',d:[2, 1, 1, 1, 1, 1],next:'q30'},
  ]},
  q30:{id:'q30',q:'A mitad de un libro, de pronto no quieres seguir—',type:'Desvío · Páginas',opts:[
    {t:'Lo cierras y vuelves otro día',d:[0, 3, 2, 3, 1, 3],next:'q14'},
    {t:'Saltas a la última página a espiar el final',d:[1, 3, 1, 2, 2, 2],next:'q14'},
    {t:'Cambias de libro — ninguno se acabará',d:[1, 2, 2, 2, 1, 2],next:'q15'},
    {t:'Miras fijamente la portada',d:[0, 3, 3, 4, 1, 2],next:'q15'},
    {t:'Huir primero, pensar después',d:[2, 1, 1, 1, 1, 1],next:'q14'},
  ]},
  q31:{id:'q31',q:'En el ascensor con alguien a quien viste una vez—',type:'Desvío · Encuentro',opts:[
    {t:'Finges mirar el móvil',d:[1, 2, 1, 2, 0, 1],next:'q15'},
    {t:'Asientes levemente, ambos en silencio',d:[0, 3, 2, 2, 2, 0],next:'q15'},
    {t:'Quieres decir algo y lo tragas',d:[1, 3, 1, 1, 2, 1],next:'q16'},
    {t:'Recuerdas su nombre pero actúas como desconocido',d:[1, 2, 2, 1, 1, 2],next:'q16'},
    {t:'Lo que sea, da igual',d:[2, 1, 1, 1, 1, 1],next:'q15'},
  ]},
  q32:{id:'q32',q:'Recibes un mensaje sin contexto—',type:'Desvío · Mensaje',opts:[
    {t:'Lo lees tres veces, adivinando quién es',d:[1, 2, 2, 1, 1, 1],next:'q18'},
    {t:'No respondes — esperas explicación',d:[1, 1, 1, 2, 1, 0],next:'q18'},
    {t:'Respondes con un signo de interrogación',d:[2, 1, 1, 1, 0, 2],next:'q19'},
    {t:'Supones error y lo deslizas',d:[1, 1, 0, 1, 1, 1],next:'q19'},
    {t:'Solo vengo de relleno',d:[2, 1, 1, 1, 1, 1],next:'q18'},
  ]},
  q33:{id:'q33',q:'En la libreta hay un ticket viejo—',type:'Desvío · Recuerdo',opts:[
    {t:'Reconstruyes ese día por la fecha',d:[0, 3, 1, 1, 2, 1],next:'q19'},
    {t:'Lo vuelves a guardar y sigues escribiendo',d:[1, 2, 2, 1, 1, 2],next:'q19'},
    {t:'Lo tiras para no evocar',d:[1, 2, 1, 1, 2, 0],next:'q20'},
    {t:'Lo fotografías y luego olvidas',d:[1, 2, 2, 2, 0, 2],next:'q20'},
    {t:'Qué raro',d:[2, 1, 1, 1, 1, 1],next:'q19'},
  ]},
  q34:{id:'q34',q:'Si solo pudieras dejar una línea en la guarda, eliges—',type:'Pregunta final',opts:[
    {t:'«Hay verdad aquí, pero al querer decirla, se pierde.»',d:[0, 3, 5, 4, 1, 2]},
    {t:'«El hombre vive por vivir.»',d:[2, 1, 0, 1, 3, 0]},
    {t:'«Big Brother is watching you»',d:[3, 0, 2, 1, 2, 2]},
    {t:'«So it goes.»',d:[2, 1, 2, 1, 1, 3]},
    {t:'Sin idea por dónde empezar',d:[2, 1, 1, 1, 1, 1]},
  ],end:true},
  q35:{id:'q35',q:'Última pregunta: ¿cómo te gustaría ser malinterpretado—',type:'Pregunta final',opts:[
    {t:'Que lean calor en el silencio',d:[0, 4, 3, 3, 2, 3]},
    {t:'Que lean filo entre las palabras',d:[4, 3, 3, 1, 3, 4]},
    {t:'Que lean artificio en la estructura',d:[1, 2, 3, 1, 0, 3]},
    {t:'Que lean nuevas posibilidades en el error',d:[1, 2, 3, 1, 0, 3]},
    {t:'Ni idea',d:[2, 1, 1, 1, 1, 1]},
  ],end:true},
  q36:{id:'q36',q:'Última pregunta: si la literatura es una ventana, quieres que—',type:'Pregunta final',opts:[
    {t:'Muestre a otros y a ti mismo',d:[2, 4, 2, 2, 4, 3]},
    {t:'Se meza al viento sin cerrarse',d:[1, 4, 2, 3, 3, 4]},
    {t:'Se abra solo un poco — basta',d:[0, 3, 3, 4, 2, 2]},
    {t:'Se abra de par en par y entre la lluvia',d:[1, 3, 2, 2, 2, 4]},
    {t:'Mente en blanco',d:[2, 1, 1, 1, 1, 1]},
  ],end:true},
};
const LIT_START = 'q01';
