/* Literary temperament questions · en */
const LIT_Q = {
  q01:{id:'q01',q:'When rain taps the window at night, you first think of—',type:'Night thoughts',opts:[
    {t:'Letters never sent, and words left unsaid',d:[1, 3, 1, 1, 2, 1],next:'q02'},
    {t:'An old road, a figure receding into distance',d:[0, 3, 1, 1, 2, 0],next:'q03'},
    {t:'How many people in the city are still awake',d:[2, 1, 2, 1, 3, 0],next:'q04'},
    {t:'The rain itself, like a dialogue without end',d:[1, 2, 3, 1, 0, 2],next:'q05'},
    {t:'That is too weird',d:[2, 1, 1, 1, 1, 1],next:'q30'},
  ]},
  q02:{id:'q02',q:'If you wrote half a sentence for this mood, it would stop at—',type:'Mood',opts:[
    {t:'"So that\'s how it is."',d:[2, 1, 2, 1, 1, 1],next:'q06'},
    {t:'"What a pity…"',d:[1, 3, 1, 1, 2, 0],next:'q07'},
    {t:'"Let it be."',d:[1, 1, 1, 1, 2, 1],next:'q08'},
    {t:'"Wait — that\'s not right."',d:[2, 0, 3, 1, 0, 2],next:'q09'},
    {t:'No idea where to start',d:[2, 1, 1, 1, 1, 1],next:'q31'},
  ]},
  q03:{id:'q03',q:'Walking into a crowd, you are more like—',type:'In the crowd',opts:[
    {t:'A cool observer taking notes',d:[2, 1, 2, 1, 1, 1],next:'q06'},
    {t:'Someone easily moved or stung',d:[0, 3, 1, 1, 3, 0],next:'q07'},
    {t:'A polite, distant passerby',d:[1, 2, 1, 2, 0, 1],next:'q08'},
    {t:'A storyteller arranging plots in secret',d:[1, 2, 3, 1, 0, 2],next:'q09'},
    {t:'I have no clue',d:[2, 1, 1, 1, 1, 1],next:'q30'},
  ]},
  q04:{id:'q04',q:'When a good book is interrupted midway, you think—',type:'Reading notes',opts:[
    {t:'I need a quiet place to finish it',d:[1, 2, 1, 1, 1, 1],next:'q06'},
    {t:'Stopping at the cliffhanger makes the aftertaste linger',d:[1, 3, 1, 1, 0, 2],next:'q07'},
    {t:'What is that character doing right now?',d:[0, 2, 2, 1, 2, 1],next:'q08'},
    {t:'Mark this page — I\'ll come back',d:[2, 1, 3, 1, 1, 2],next:'q09'},
    {t:'My mind goes blank',d:[2, 1, 1, 1, 1, 1],next:'q31'},
  ]},
  q05:{id:'q05',q:'The word "homesickness" first brings not a place, but—',type:'Homesickness',opts:[
    {t:'A tone you can never return to',d:[0, 3, 1, 1, 2, 0],next:'q06'},
    {t:'Old objects, old sounds, old scents',d:[0, 3, 0, 1, 3, 0],next:'q07'},
    {t:'Your reckless, sincere younger self',d:[1, 2, 1, 1, 2, 1],next:'q08'},
    {t:'Time itself rolling backward',d:[1, 2, 3, 1, 1, 2],next:'q09'},
    {t:'What is this asking?',d:[2, 1, 1, 1, 1, 1],next:'q30'},
  ]},
  q06:{id:'q06',q:'Which silence do you know best—',type:'Silence',opts:[
    {t:'Two people saying nothing, yet understanding',d:[0, 2, 1, 1, 3, 0],next:'q10'},
    {t:'Those few seconds of clarity in a noisy room',d:[1, 1, 2, 2, 0, 1],next:'q10'},
    {t:'The long stretch after swallowing your words',d:[2, 2, 1, 1, 2, 0],next:'q30'},
    {t:'Wanting to speak but finding no exact word',d:[1, 2, 3, 1, 0, 2],next:'q31'},
    {t:'Escape first, think later',d:[2, 1, 1, 1, 1, 1],next:'q31'},
  ]},
  q07:{id:'q07',q:'When you write, the first thing to land is often—',type:'At the pen',opts:[
    {t:'A question that refuses compromise',d:[3, 0, 2, 0, 1, 1],next:'q11'},
    {t:'A concrete scene: window, lamp, rain',d:[0, 3, 1, 1, 1, 1],next:'q11'},
    {t:'A line of poetry without beginning or end',d:[0, 3, 2, 1, 1, 2],next:'q30'},
    {t:'A strange yet captivating premise',d:[1, 1, 3, 1, 0, 3],next:'q31'},
    {t:'Whatever, anything works',d:[2, 1, 1, 1, 1, 1],next:'q30'},
  ]},
  q08:{id:'q08',q:'When hurt runs too deep to speak, you usually—',type:'Restraint',opts:[
    {t:'Write it down, or turn it over in your mind',d:[2, 2, 2, 1, 1, 2],next:'q12'},
    {t:'Pretend nothing happened and carry on',d:[1, 1, 0, 1, 3, 0],next:'q12'},
    {t:'Withdraw from people until the feeling sinks',d:[0, 2, 1, 2, 1, 0],next:'q30'},
    {t:'Laugh suddenly to change the mood',d:[1, 1, 0, 1, 2, 2],next:'q31'},
    {t:'I\'m just here for the ride',d:[2, 1, 1, 1, 1, 1],next:'q31'},
  ]},
  q09:{id:'q09',q:'Which light relaxes you most easily—',type:'Light',opts:[
    {t:'Dusk fading, the sky neither bright nor dark',d:[0, 3, 1, 1, 1, 1],next:'q13'},
    {t:'First light through morning mist',d:[0, 3, 1, 1, 2, 1],next:'q13'},
    {t:'The warm circle of a desk lamp at night',d:[0, 2, 2, 2, 1, 1],next:'q30'},
    {t:'Midday white, too blunt to hide in',d:[2, 1, 2, 1, 2, 2],next:'q31'},
    {t:'That is too weird',d:[2, 1, 1, 1, 1, 1],next:'q30'},
  ]},
  q10:{id:'q10',q:'If you compared yourself to a season, you are closer to—',type:'Seasons',opts:[
    {t:'Late spring: abundance already tinged with decay',d:[1, 3, 1, 1, 2, 1],next:'q14'},
    {t:'Long summer: humid, endless, unwilling to leave',d:[2, 2, 2, 1, 1, 2],next:'q14'},
    {t:'Deep autumn: crisp, clear, slightly looking back',d:[1, 2, 2, 1, 2, 1],next:'q32'},
    {t:'Late winter: cold, still, yet holding renewal',d:[2, 1, 3, 1, 1, 2],next:'q33'},
    {t:'No idea where to start',d:[2, 1, 1, 1, 1, 1],next:'q31'},
  ]},
  q11:{id:'q11',q:'Hearing of disaster far away, your first reaction is more like—',type:'Distant news',opts:[
    {t:'Demanding the cause, refusing easy acceptance',d:[3, 0, 2, 0, 2, 1],next:'q15'},
    {t:'A sinking heart that takes long to recover',d:[1, 3, 1, 1, 3, 0],next:'q15'},
    {t:'Silence first, piecing details together',d:[2, 1, 2, 1, 2, 1],next:'q32'},
    {t:'Finding it absurd, yet unable to laugh it off',d:[2, 1, 3, 1, 1, 3],next:'q33'},
    {t:'I have no clue',d:[2, 1, 1, 1, 1, 1],next:'q30'},
  ]},
  q12:{id:'q12',q:'A good story — where would you want it to begin—',type:'Opening lines',opts:[
    {t:'A small matter that mirrors an entire age',d:[3, 1, 1, 1, 3, 0],next:'q16'},
    {t:'A chance meeting where mood precedes plot',d:[1, 3, 1, 1, 1, 1],next:'q16'},
    {t:'A riddle, or one irregular detail',d:[1, 1, 3, 1, 0, 3],next:'q32'},
    {t:'The instant everyday life cracks open',d:[2, 2, 1, 1, 2, 2],next:'q33'},
    {t:'My mind goes blank',d:[2, 1, 1, 1, 1, 1],next:'q31'},
  ]},
  q13:{id:'q13',q:'Saying goodbye to a friend, you often say or do—',type:'Farewell',opts:[
    {t:'Say little, but look once more',d:[1, 2, 1, 1, 2, 0],next:'q17'},
    {t:'Light words to cover the weight',d:[1, 2, 0, 1, 2, 2],next:'q17'},
    {t:'Suddenly mention something unrelated',d:[1, 3, 1, 1, 1, 2],next:'q32'},
    {t:'Make "goodbye" sound like "until we meet again"',d:[0, 3, 1, 1, 2, 1],next:'q33'},
    {t:'What is this asking?',d:[2, 1, 1, 1, 1, 1],next:'q30'},
  ]},
  q14:{id:'q14',q:'Waking from a dream, what lingers on the pillow is often—',type:'Waking',opts:[
    {t:'An emotion you cannot name',d:[0, 3, 1, 1, 1, 2],next:'q18'},
    {t:'A clear image, like an old photograph',d:[0, 3, 1, 1, 2, 1],next:'q18'},
    {t:'A line of dialogue from the dream, still remembered',d:[1, 2, 2, 1, 1, 2],next:'q22'},
    {t:'Only blankness, yet feeling something lost',d:[1, 2, 3, 2, 0, 2],next:'q23'},
    {t:'Escape first, think later',d:[2, 1, 1, 1, 1, 1],next:'q31'},
  ]},
  q15:{id:'q15',q:'At a street corner where the light is just right, you—',type:'Street corner',opts:[
    {t:'Stop and watch the crowd and shadows',d:[1, 2, 1, 1, 1, 0],next:'q19'},
    {t:'Think of someone old, unrelated to this moment',d:[0, 3, 1, 1, 2, 0],next:'q19'},
    {t:'Reach for your phone, fearing you cannot capture the mood',d:[1, 2, 1, 2, 0, 1],next:'q22'},
    {t:'Feel this moment should not be disturbed',d:[0, 2, 2, 2, 1, 1],next:'q23'},
    {t:'Whatever, anything works',d:[2, 1, 1, 1, 1, 1],next:'q30'},
  ]},
  q16:{id:'q16',q:'Your first instinct about "the absurd" is—',type:'Absurdity',opts:[
    {t:'The normal state of things — no need to be shocked',d:[2, 1, 2, 1, 2, 2],next:'q20'},
    {t:'Hollowness beneath a gorgeous surface',d:[2, 2, 1, 1, 1, 2],next:'q20'},
    {t:'A cold joke fate plays on us',d:[1, 2, 2, 1, 1, 3],next:'q22'},
    {t:'Someone using absurdity as a fig leaf',d:[3, 0, 2, 1, 2, 2],next:'q23'},
    {t:'I\'m just here for the ride',d:[2, 1, 1, 1, 1, 1],next:'q31'},
  ]},
  q17:{id:'q17',q:'If you had to give up one thing, you would least let go of—',type:'Choice',opts:[
    {t:'The courage to tell the truth',d:[3, 0, 2, 0, 2, 1],next:'q21'},
    {t:'Acute sensitivity to and attachment to beauty',d:[0, 3, 2, 1, 1, 2],next:'q21'},
    {t:'Bonds with a few chosen people',d:[0, 2, 0, 1, 4, 0],next:'q24'},
    {t:'Room to think independently',d:[2, 1, 3, 1, 0, 2],next:'q25'},
    {t:'That is too weird',d:[2, 1, 1, 1, 1, 1],next:'q30'},
  ]},
  q18:{id:'q18',q:'Alone, what you enjoy most is—',type:'Solitude',opts:[
    {t:'Doing nothing, letting time pass',d:[0, 2, 2, 2, 1, 0],next:'q22'},
    {t:'Reading, listening to wind, talking with yourself',d:[1, 2, 3, 1, 1, 1],next:'q22'},
    {t:'Putting the small days in order',d:[2, 0, 1, 1, 2, 0],next:'q26'},
    {t:'Letting thoughts wander, noting stray ideas',d:[1, 2, 3, 1, 0, 3],next:'q27'},
    {t:'No idea where to start',d:[2, 1, 1, 1, 1, 1],next:'q31'},
  ]},
  q19:{id:'q19',q:'If you could keep only speaking or writing—',type:'Expression',opts:[
    {t:'Writing. Words spoken too easily distort',d:[1, 2, 2, 1, 1, 2],next:'q23'},
    {t:'Speaking. Writing is too slow for the heartbeat',d:[0, 3, 1, 1, 2, 1],next:'q23'},
    {t:'Neither much — silence is more honest',d:[1, 1, 2, 2, 1, 1],next:'q26'},
    {t:'Another way: drawing, walking, or simply watching',d:[1, 2, 3, 1, 0, 2],next:'q27'},
    {t:'I have no clue',d:[2, 1, 1, 1, 1, 1],next:'q30'},
  ]},
  q20:{id:'q20',q:'Which kind of sentence moves you more easily?',type:'Language taste',opts:[
    {t:'Direct, sharp, with a sting',d:[3, 0, 1, 1, 1, 2],next:'q24'},
    {t:'Quiet, weighty, like a long take',d:[1, 3, 1, 0, 3, 0],next:'q24'},
    {t:'Cool, beautiful, with a little distance',d:[2, 2, 1, 2, 0, 1],next:'q28'},
    {t:'Abstract, leaping, making you think',d:[1, 1, 3, 1, 0, 3],next:'q29'},
    {t:'My mind goes blank',d:[2, 1, 1, 1, 1, 1],next:'q31'},
  ]},
  q21:{id:'q21',q:'In a team, you usually play the role of—',type:'Collaboration',opts:[
    {t:'The one who points out problems',d:[3, 0, 1, 0, 1, 1],next:'q25'},
    {t:'The one who eases the mood',d:[0, 2, 0, 1, 3, 0],next:'q25'},
    {t:'The one who works quietly',d:[1, 0, 0, 1, 2, 0],next:'q28'},
    {t:'The one who proposes odd ideas',d:[1, 2, 2, 1, 0, 3],next:'q29'},
    {t:'What is this asking?',d:[2, 1, 1, 1, 1, 1],next:'q30'},
  ]},
  q22:{id:'q22',q:'On an empty afternoon, you first notice—',type:'Afternoon',opts:[
    {t:'Sunlight moving slowly across the floor',d:[0, 2, 2, 2, 1, 1],next:'q26'},
    {t:'Distant, faint city sounds',d:[1, 2, 1, 1, 2, 0],next:'q26'},
    {t:'Things you have not yet finished',d:[2, 1, 2, 1, 2, 1],next:'q34'},
    {t:'Time suddenly slowing down',d:[1, 2, 3, 1, 1, 2],next:'q35'},
    {t:'Escape first, think later',d:[2, 1, 1, 1, 1, 1],next:'q31'},
  ]},
  q23:{id:'q23',q:'An old locust tree beside the post road — you would—',type:'Post road',opts:[
    {t:'Rest beneath it, listening to the wind tell old tales',d:[0, 3, 2, 3, 3, 2],next:'q27'},
    {t:'Fold a leaf into unfinished manuscript pages',d:[1, 4, 2, 2, 2, 4],next:'q27'},
    {t:'Remember a parting and stop for a long while',d:[1, 4, 1, 2, 3, 2],next:'q34'},
    {t:'Keep walking without looking back',d:[3, 2, 2, 1, 4, 2],next:'q35'},
    {t:'Whatever, anything works',d:[2, 1, 1, 1, 1, 1],next:'q30'},
  ]},
  q24:{id:'q24',q:'Window paper stirred by wind, like an unread page. You—',type:'Window paper',opts:[
    {t:'Reach out to hold it, afraid it will fly away',d:[1, 4, 1, 2, 2, 2],next:'q28'},
    {t:'Let it rustle as background',d:[0, 3, 3, 3, 1, 3],next:'q28'},
    {t:'Open the window and let the wind in',d:[0, 3, 2, 4, 2, 3],next:'q36'},
    {t:'Shut the window tight and light a lamp',d:[1, 3, 3, 3, 2, 2],next:'q34'},
    {t:'I\'m just here for the ride',d:[2, 1, 1, 1, 1, 1],next:'q31'},
  ]},
  q25:{id:'q25',q:'When tea steam rises, you think of—',type:'Tea steam',opts:[
    {t:'Old friends around the hearth, few words needed',d:[1, 3, 1, 2, 4, 1],next:'q29'},
    {t:'Sitting alone, perfect for writing',d:[0, 3, 3, 4, 1, 3],next:'q29'},
    {t:'Life like tea — bitter first, sweet after',d:[2, 3, 3, 1, 4, 2],next:'q36'},
    {t:'Tea grows cold, and people disperse',d:[1, 4, 2, 2, 3, 2],next:'q35'},
    {t:'That is too weird',d:[2, 1, 1, 1, 1, 1],next:'q30'},
  ]},
  q26:{id:'q26',q:'Seeing geese fly south, what stirs in you—',type:'Returning geese',opts:[
    {t:'Thoughts of home, needing no words',d:[1, 4, 1, 2, 4, 2],next:'q34'},
    {t:'The vast world, the small self',d:[1, 3, 4, 2, 2, 3],next:'q34'},
    {t:'Wanting to follow the geese and see far places',d:[0, 3, 2, 3, 2, 4],next:'q35'},
    {t:'Breaking a reed to give a traveler',d:[0, 4, 1, 2, 3, 2],next:'q36'},
    {t:'No idea where to start',d:[2, 1, 1, 1, 1, 1],next:'q31'},
  ]},
  q27:{id:'q27',q:'An ancient temple bell — its echo in the valley. You—',type:'Temple bell',opts:[
    {t:'Listen with folded hands until the sound fades',d:[0, 3, 5, 3, 2, 2],next:'q35'},
    {t:'Remember a line you never finished writing',d:[1, 4, 2, 2, 2, 4],next:'q35'},
    {t:'Turn and leave, not disturbing the quiet',d:[1, 2, 3, 3, 2, 2],next:'q36'},
    {t:'Push open the gate and borrow a book',d:[2, 3, 4, 2, 3, 3],next:'q34'},
    {t:'I have no clue',d:[2, 1, 1, 1, 1, 1],next:'q30'},
  ]},
  q28:{id:'q28',q:'Moonlight through paper window, like—',type:'Moonlight',opts:[
    {t:'A letter never sent, folded in your sleeve',d:[1, 4, 1, 2, 2, 2],next:'q36'},
    {t:'Old years and old matters suddenly clear',d:[1, 4, 2, 2, 3, 2],next:'q34'},
    {t:'A small path leading to the unknown',d:[0, 3, 3, 3, 1, 4],next:'q35'},
    {t:'Mercury spilled — brightness everywhere',d:[0, 4, 2, 2, 1, 5],next:'q36'},
    {t:'My mind goes blank',d:[2, 1, 1, 1, 1, 1],next:'q31'},
  ]},
  q29:{id:'q29',q:'Wanting to tell someone your heart — in the end you—',type:'Secret heart',opts:[
    {t:'Write it into words and give it to the spring wind',d:[1, 4, 2, 2, 2, 4],next:'q34'},
    {t:'Tell a confidant, in only a few lines',d:[1, 3, 1, 2, 4, 1],next:'q35'},
    {t:'Swallow it back into a long sigh',d:[2, 4, 2, 2, 3, 2],next:'q36'},
    {t:'Tell the mountains and rivers — no answer needed',d:[0, 3, 4, 4, 2, 3],next:'q36'},
    {t:'What is this asking?',d:[2, 1, 1, 1, 1, 1],next:'q30'},
  ]},
  q30:{id:'q30',q:'Midway through a book, you suddenly don\'t want to read—',type:'Detour · Pages',opts:[
    {t:'Close it and return another day',d:[0, 3, 2, 3, 1, 3],next:'q14'},
    {t:'Jump to the last page and peek at the ending',d:[1, 3, 1, 2, 2, 2],next:'q14'},
    {t:'Switch books — none will be finished anyway',d:[1, 2, 2, 2, 1, 2],next:'q15'},
    {t:'Stare blankly at the title page',d:[0, 3, 3, 4, 1, 2],next:'q15'},
    {t:'Escape first, think later',d:[2, 1, 1, 1, 1, 1],next:'q14'},
  ]},
  q31:{id:'q31',q:'In an elevator with someone you\'ve met once—',type:'Detour · Encounter',opts:[
    {t:'Pretend to check your phone',d:[1, 2, 1, 2, 0, 1],next:'q15'},
    {t:'Nod slightly, both silent',d:[0, 3, 2, 2, 2, 0],next:'q15'},
    {t:'Suddenly want to say something, then swallow it',d:[1, 3, 1, 1, 2, 1],next:'q16'},
    {t:'Remember their name but act like a stranger',d:[1, 2, 2, 1, 1, 2],next:'q16'},
    {t:'Whatever, anything works',d:[2, 1, 1, 1, 1, 1],next:'q15'},
  ]},
  q32:{id:'q32',q:'Receiving a message with no context—',type:'Detour · Message',opts:[
    {t:'Read it three times, guessing who sent it',d:[1, 2, 2, 1, 1, 1],next:'q18'},
    {t:'Don\'t reply — wait for an explanation',d:[1, 1, 1, 2, 1, 0],next:'q18'},
    {t:'Reply with a question mark',d:[2, 1, 1, 1, 0, 2],next:'q19'},
    {t:'Assume it was sent by mistake and swipe away',d:[1, 1, 0, 1, 1, 1],next:'q19'},
    {t:'I\'m just here for the ride',d:[2, 1, 1, 1, 1, 1],next:'q18'},
  ]},
  q33:{id:'q33',q:'An old ticket stub tucked in your notebook—',type:'Detour · Keepsake',opts:[
    {t:'Trace that day by the date',d:[0, 3, 1, 1, 2, 1],next:'q19'},
    {t:'Tuck it back and keep writing something else',d:[1, 2, 2, 1, 1, 2],next:'q19'},
    {t:'Throw it away to avoid nostalgia',d:[1, 2, 1, 1, 2, 0],next:'q20'},
    {t:'Photograph it, then forget',d:[1, 2, 2, 2, 0, 2],next:'q20'},
    {t:'That is too weird',d:[2, 1, 1, 1, 1, 1],next:'q19'},
  ]},
  q34:{id:'q34',q:'If you could leave one line on the flyleaf, you choose—',type:'Final question',opts:[
    {t:'"There is true meaning here, but words fail once I try to grasp it."',d:[0, 3, 5, 4, 1, 2]},
    {t:'"People live for the sake of living itself."',d:[2, 1, 0, 1, 3, 0]},
    {t:'"Big Brother is watching you"',d:[3, 0, 2, 1, 2, 2]},
    {t:'"So it goes."',d:[2, 1, 2, 1, 1, 3]},
    {t:'No idea where to start',d:[2, 1, 1, 1, 1, 1]},
  ],end:true},
  q35:{id:'q35',q:'Final question: how would you like to be misread—',type:'Final question',opts:[
    {t:'Finding warmth in silence',d:[0, 4, 3, 3, 2, 3]},
    {t:'Finding edge in the gaps between words',d:[4, 3, 3, 1, 3, 4]},
    {t:'Finding craft in the structure',d:[1, 2, 3, 1, 0, 3]},
    {t:'Finding new possibilities in misreading',d:[1, 2, 3, 1, 0, 3]},
    {t:'I have no clue',d:[2, 1, 1, 1, 1, 1]},
  ],end:true},
  q36:{id:'q36',q:'Final question: if literature is a window, you want it to—',type:'Final question',opts:[
    {t:'Show others and show yourself',d:[2, 4, 2, 2, 4, 3]},
    {t:'Sway in the wind but never close',d:[1, 4, 2, 3, 3, 4]},
    {t:'Open just a crack — enough is enough',d:[0, 3, 3, 4, 2, 2]},
    {t:'Push wide and let the rain in too',d:[1, 3, 2, 2, 2, 4]},
    {t:'My mind goes blank',d:[2, 1, 1, 1, 1, 1]},
  ],end:true},
};
const LIT_START = 'q01';
